
export enum ConfirmBookingTypes {
    GET_RESERVATION_QUESTION = '[Confirm Booking] GET_RESERVATION_QUESTION',
    GET_RESERVATION_QUESTION_SUCCESS = '[Confirm Booking] GET_RESERVATION_QUESTION_SUCCESS',
    GET_RESERVATION_QUESTION_FAIL = '[Confirm Booking] GET_RESERVATION_QUESTION_FAIL',

    UPDATE_BATCH = '[Confirm Booking] UPDATE_BATCH',
    UPDATE_BATCH_SUCCESS = '[Confirm Booking] UPDATE_BATCH_SUCCESS',
    UPDATE_BATCH_FAIL = '[Confirm Booking] GET_RESERVATION_QUESTION_FAIL',
}
