export enum authTypes {
  GET_ACCESS_TOKEN = '[Auth] GET_ACCESS_TOKEN',
  GET_ACCESS_TOKEN_SUCCESS = '[Auth] GET_ACCESS_TOKEN_SUCCESS',
  GET_ACCESS_TOKEN_FAIL = '[Auth] GET_ACCESS_TOKEN_FAIL',

  GET_CLIENT_SESSION = '[Auth] GET_CLIENT_SESSION',
  GET_CLIENT_SESSION_SUCCESS = '[Auth] GET_CLIENT_SESSION_SUCCESS',
  GET_CLIENT_SESSION_FAIL = '[Auth] GET_CLIENT_SESSION_FAIL',

  GET_MYSTAYS_TOKEN = '[Auth] GET_MYSTAYS_TOKEN',
  GET_MYSTAYS_TOKEN_SUCCESS = '[Auth] GET_MYSTAYS_TOKEN_SUCCESS',
  GET_MYSTAYS_TOKEN_FAIL = '[Auth] GET_MYSTAYS_TOKEN_FAIL'
}
